CREATE TABLE Usuario (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR (100),
    NOME VARCHAR(100),
    CPF VARCHAR(11)

);

CREATE TABLE VACINACAO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    VACINA VARCHAR(100),
    EMAIL VARCHAR(100),
    DATA VARCHAR(100)
);


